#!/bin/bash

# Ensure the script can access the locally-installed versions of npm-managed tools
PATH=node_modules/.bin:$PATH

main() {
  set_script_sources_to_dev_filenames
  watch_js
}

set_script_sources_to_dev_filenames() {
  echo "Updating script tags' src attributes..."
  sub_dev_creator_filename
  sub_dev_sources_filename
}

watch_js() {
  echo "Watching js files..."
  rollup --watch --config rollup.encode_url.config.js --file dist/creator.js &
  rollup --watch --config rollup.parse_url.config.js --file citation/dist/sources.js
}

sub_dev_creator_filename() {
  sed "s_/[^/]*creator.js_/creator.js_" index.html > newindex.html
  mv newindex.html index.html
}

sub_dev_sources_filename() {
  sed "s_/[^/]*sources.js_/sources.js_" citation/index.html > citation/newindex.html
  mv citation/newindex.html citation/index.html
}

main

# vim:foldmethod=marker:foldmarker={,}:foldlevel=0
